### ISSUE TITLE
Error executing simple sequence

### ISSUE THREAD

**Issue by albertiniufu** [amandaclare/lyndon-factors#2]
Running file created the following way:

echo -e ">longA\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" > as.fna

I get the error:

Traceback (most recent call last):
  File "enhanced_factors.py", line 345, in <module>
    r = alg1(s, m, no_backtrack = True)
  File "enhanced_factors.py", line 255, in alg1
    good = assign_to_Xs(m, facs, Xs)
  File "enhanced_factors.py", line 197, in assign_to_Xs
    (e, X_vals) = next(sorted_exponents)
StopIteration

**Comment by amandaclare** [comment]
Sorry, that was a bug. Thanks for finding it! Now hopefully fixed and pushed.
